### PR TITLE
Document the migration procedure to Astarte Kubernetes Operator 22.11

### PR DESCRIPTION
**Pull request by Annopaolo**
Document the upgrade to Astarte Kubernetes Operator 22.11 and the Astarte, Flow, AVI storage version upgrade to `v1alpha2`. See [the related issue](https://github.com/astarte-platform/astarte-kubernetes-operator/issues/298).

### CODE REVIEW

**Comment by Annopaolo** [comment]
Depends on https://github.com/astarte-platform/astartectl/pull/162 and https://github.com/astarte-platform/astarte-kubernetes-operator/pull/297.

**Review by matt-mazzucato — CHANGES_REQUESTED** [review]
Also, an entry should be added [here](https://github.com/astarte-platform/astarte/blob/master/doc/pages/upgrade/000-upgrade_index.md)

**Review by matt-mazzucato — APPROVED** [review]

**Review by matt-mazzucato — CHANGES_REQUESTED** [review]
According to astarte-platform/astarte-kubernetes-operator/issues/306, the new versions will be in the form of `<YY>.<0M>.<0m>`. Please, fix the "micro" part padding it with a zero.

**Review by matt-mazzucato — APPROVED** [review]

**Comment by matt-mazzucato** [comment]
The content of the PR is approved. However, according to astarte-platform/astarte-kubernetes-operator/issues/308, the upgrade guide will belong to the astarte operator repository.
This PR will be closed as soon as its content will be moved to the proper location.

**Comment by Annopaolo** [comment]
Closing as this guide now belongs to the astarte-kubernetes-operator repository. The guide is now found at https://github.com/astarte-platform/astarte-kubernetes-operator/pull/315.

**Pull request closed without merging**
